// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kk4wRUQIKJdwQYtstjnqblWbF75emfk',
    appId: '1:769176418060:web:2a4fa2c7ed9c85c7837b29',
    messagingSenderId: '769176418060',
    projectId: 'sintir-2f0be',
    authDomain: 'sintir-2f0be.firebaseapp.com',
    storageBucket: 'sintir-2f0be.appspot.com',
    measurementId: 'G-PDZHWQK8MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqFN733F9JsJf88OE-d-3GtddIzDiXNPA',
    appId: '1:769176418060:android:bed9337fd11ff52c837b29',
    messagingSenderId: '769176418060',
    projectId: 'sintir-2f0be',
    storageBucket: 'sintir-2f0be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5X4c7bRzpxVujIjyUgXcSYyQtSqZdW8',
    appId: '1:769176418060:ios:4e28804decb7de53837b29',
    messagingSenderId: '769176418060',
    projectId: 'sintir-2f0be',
    storageBucket: 'sintir-2f0be.appspot.com',
    androidClientId:
        '769176418060-1205tv1mu7qohs1122hm6h91hdbplcch.apps.googleusercontent.com',
    iosClientId:
        '769176418060-jl97he6j82c8q91v3i5be8ngjlkvdb6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sintir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5X4c7bRzpxVujIjyUgXcSYyQtSqZdW8',
    appId: '1:769176418060:ios:4e28804decb7de53837b29',
    messagingSenderId: '769176418060',
    projectId: 'sintir-2f0be',
    storageBucket: 'sintir-2f0be.appspot.com',
    androidClientId:
        '769176418060-1205tv1mu7qohs1122hm6h91hdbplcch.apps.googleusercontent.com',
    iosClientId:
        '769176418060-jl97he6j82c8q91v3i5be8ngjlkvdb6u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sintir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_kk4wRUQIKJdwQYtstjnqblWbF75emfk',
    appId: '1:769176418060:web:e2371cd66c51c2d9837b29',
    messagingSenderId: '769176418060',
    projectId: 'sintir-2f0be',
    authDomain: 'sintir-2f0be.firebaseapp.com',
    storageBucket: 'sintir-2f0be.appspot.com',
    measurementId: 'G-HJRT2CD135',
  );
}
