// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQKDkveleguXjXVokfzY-xXX3N9OABr8',
    appId: '1:225896905150:web:7d2af245080c51eeb761ef',
    messagingSenderId: '225896905150',
    projectId: 'chat-app-47e62',
    authDomain: 'chat-app-47e62.firebaseapp.com',
    databaseURL: 'https://chat-app-47e62-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-47e62.appspot.com',
    measurementId: 'G-PEHS8XLVEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDErjIrH1pFs3cEo_MOglUG9Ni9lPhgwyU',
    appId: '1:225896905150:android:3c802a945c4f76cdb761ef',
    messagingSenderId: '225896905150',
    projectId: 'chat-app-47e62',
    databaseURL: 'https://chat-app-47e62-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-47e62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ-yb-bRgTO1Gc3S4_XyvcAovUZZyqwZ4',
    appId: '1:225896905150:ios:2b0548c20c4729a7b761ef',
    messagingSenderId: '225896905150',
    projectId: 'chat-app-47e62',
    databaseURL: 'https://chat-app-47e62-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-47e62.appspot.com',
    iosBundleId: 'com.example.sintir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ-yb-bRgTO1Gc3S4_XyvcAovUZZyqwZ4',
    appId: '1:225896905150:ios:2b0548c20c4729a7b761ef',
    messagingSenderId: '225896905150',
    projectId: 'chat-app-47e62',
    databaseURL: 'https://chat-app-47e62-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-47e62.appspot.com',
    iosBundleId: 'com.example.sintir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSQKDkveleguXjXVokfzY-xXX3N9OABr8',
    appId: '1:225896905150:web:1538dc242897c41db761ef',
    messagingSenderId: '225896905150',
    projectId: 'chat-app-47e62',
    authDomain: 'chat-app-47e62.firebaseapp.com',
    databaseURL: 'https://chat-app-47e62-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-47e62.appspot.com',
    measurementId: 'G-RB6H1LLBYG',
  );
}
