// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4n1gkHdrRdcDmCMAUBmXbbwM_AkbvsaE',
    appId: '1:486293927261:web:d7e6178f17c9d2bfcb64b4',
    messagingSenderId: '486293927261',
    projectId: 'sintir-c1f40',
    authDomain: 'sintir-c1f40.firebaseapp.com',
    storageBucket: 'sintir-c1f40.appspot.com',
    measurementId: 'G-66SN1711Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQVn7mhD-5ITb_X2MfeX7_mEAQrxXfi3I',
    appId: '1:486293927261:android:c7a956cd43bad103cb64b4',
    messagingSenderId: '486293927261',
    projectId: 'sintir-c1f40',
    storageBucket: 'sintir-c1f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2rxF5o4ZttAeLPGvDuCNAU235O-8bK-4',
    appId: '1:486293927261:ios:8061ed1d97d667cccb64b4',
    messagingSenderId: '486293927261',
    projectId: 'sintir-c1f40',
    storageBucket: 'sintir-c1f40.appspot.com',
    iosBundleId: 'com.example.sintir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2rxF5o4ZttAeLPGvDuCNAU235O-8bK-4',
    appId: '1:486293927261:ios:8061ed1d97d667cccb64b4',
    messagingSenderId: '486293927261',
    projectId: 'sintir-c1f40',
    storageBucket: 'sintir-c1f40.appspot.com',
    iosBundleId: 'com.example.sintir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4n1gkHdrRdcDmCMAUBmXbbwM_AkbvsaE',
    appId: '1:486293927261:web:c14b8ad06f9f967dcb64b4',
    messagingSenderId: '486293927261',
    projectId: 'sintir-c1f40',
    authDomain: 'sintir-c1f40.firebaseapp.com',
    storageBucket: 'sintir-c1f40.appspot.com',
    measurementId: 'G-0ZYVL4YWD0',
  );
}
